### ISSUE TITLE
Is there any documentation for users? 

### ISSUE THREAD

**Issue by WulfricLee** [Qti3e/Impress-full#1]
Since it's been a long time from first commit. I wonder if this repo is still under maintenance?
I'm curious about background color change by **step**s.

**Comment by qti3e** [comment]
Hi
I don't work on this project anymore but yes there is a simple document at the end of demo presentation
http://qti3e.github.io/Impress-full/#/step-30
this URL is about background colors.
The background attributes are the same as CSS attributes:
data-background
data-background-color
data-background-image
data-background-size
data-background-repeat

**Comment by WulfricLee** [comment]
Thank you for replying me, that would be helpful.😊

**Comment by qti3e** [comment]
Your welcome :-)
